---
- name: Update puppet modules
  hosts: all
  gather_facts: yes
  tasks:
    - shell: |
        pushd /etc/puppet
        PUPPETFILE=/home/centos/ionic-cloud/puppet/Puppetfile r10k puppetfile install -v
        cp -a /home/centos/ionic-cloud/puppet/modules/ionic modules/
        popd

- name: Update controller
  hosts: controller
  gather_facts: no
  tasks:
    - shell: puppet apply -e "include ::ionic_cloud::controller"

- name: Update compute nodes
  hosts: compute
  gather_facts: no
  tasks:
    - shell: puppet apply -e "include ::ionic_cloud::compute"
